# Generated by Django 4.1.3 on 2022-11-24 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='Active', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='driver', related_query_name='driver', to=settings.AUTH_USER_MODEL)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', related_query_name='from_city', to='common.city')),
                ('passengers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city', related_query_name='to_city', to='common.city')),
            ],
        ),
    ]
