# Generated by Django 4.1.3 on 2022-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_transport_taken_seats_transport_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
