# Generated by Django 4.1.3 on 2022-11-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_alter_transport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
