# Generated by Django 4.1.3 on 2022-11-25 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transports', '0004_alter_transport_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='requests', related_query_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transport',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='passengers', related_query_name='passengers', to=settings.AUTH_USER_MODEL),
        ),
    ]
