# Generated by Django 4.1.3 on 2022-11-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0005_transport_requests_alter_transport_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='taken_seats',
        ),
    ]
