# Generated by Django 4.1.3 on 2022-11-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0006_remove_transport_taken_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
