# Generated by Django 4.1.3 on 2022-12-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0007_transport_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='time',
            field=models.TimeField(blank=True, default='Not set', null=True),
        ),
    ]
