# Generated by Django 4.1.3 on 2022-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0009_transport_chatroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='ACTIVE', max_length=20),
        ),
    ]
