# Generated by Django 4.1.3 on 2022-12-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0011_alter_transport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
