# Generated by Django 4.1.3 on 2022-12-13 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transports', '0012_alter_transport_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', related_query_name='driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
