# Generated by Django 4.1.3 on 2022-12-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cities'},
        ),
    ]
