# Generated by Django 4.1.3 on 2022-12-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_city_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
